### ISSUE TITLE
ReconInput has no attribute host_dict

### ISSUE THREAD

**Issue by rlhadas** [ssantichaivekin/eMPRess#107]
In the renaming of input arguments, something seems to have gotten mixed-up...

I get this error...

(empress) Desktop/empress % python empress_gui.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/ran/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "empress_gui.py", line 390, in plot_cost_regions
    cost_regions = empress.compute_cost_regions(self.recon_input, 0.5, 10, 0.5, 10)
  File "/Users/ran/Desktop/empress/empress/__init__.py", line 220, in compute_cost_regions
    parasite_dict = recon_input.parasite_dict
AttributeError: 'ReconInput' object has no attribute 'parasite_dict'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/ran/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "empress_gui.py", line 539, in display_recon_information
    App.recon_graph = empress.reconcile(self.recon_input, self.dup_cost, self.trans_cost, self.loss_cost)
  File "/Users/ran/Desktop/empress/empress/__init__.py", line 232, in reconcile
    graph, total_cost, n_recon, roots = recongraph_tools.DP(recon_input, dup_cost, trans_cost, loss_cost)
  File "/Users/ran/Desktop/empress/empress/reconcile/recongraph_tools.py", line 109, in DP
    host_dict = tree_data.host_dict
AttributeError: 'ReconInput' object has no attribute 'host_dict'

**Comment by ssantichaivekin** [comment]
May I ask which branch you are working on?

**Comment by ssantichaivekin** [comment]
If this is not on master, you might want to comment directly to the corresponding pull request.
