### ISSUE TITLE
cli: filename not passed as one of the arguments for cluster command

### ISSUE THREAD

**Issue by JingyiRose** [ssantichaivekin/empress#168]
In ``cluster_main.py``,  the function ``perform_clustering`` uses ``args.filename``,  but filename is not one of the arguments passed in. When I run ``python empress_cli.py cluster examples/heliconius_host.nwk examples/heliconius_parasite.nwk examples/heliconius_mapping.mapping 3 --medians --depth 5 --pdv-vis --pdv -d 1 -t 1 -l 1 ``, the following error is produced:
```python
Traceback (most recent call last):
  File "empress_cli.py", line 68, in <module>
    main()
  File "empress_cli.py", line 64, in main
    cli_commands.cluster.run_cluster(args)
  File "/Users/jingyiliu/Desktop/eMPRess/cli_commands/cluster.py", line 40, in run_cluster
    cluster_main.perform_clustering(recon_input, args.dup_cost, args.trans_cost, args.loss_cost, args.n_clusters, args)
  File "/Users/jingyiliu/Desktop/eMPRess/empress/cluster/cluster_main.py", line 168, in perform_clustering
    pdv_vis(species_tree, gene_tree, gene_root, recon_g, graphs, args, args.filename)
AttributeError: 'Namespace' object has no attribute 'filename'
```

**Comment by ssantichaivekin** [comment]
I tested the code with the current master and it seems the issue has been fixed.
