### ISSUE TITLE
Could not find lib c or load any of its variants []

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#231]
Running empress from the command line produces this error:
```
(empress) bash-3.2$ python3.7 empress_gui.py 
Traceback (most recent call last): 
  File "empress_gui.py", line 15, in <module> 
    import empress 
  File "/Users/sunilkumar/Dropbox/College Docs/Senior Year/research/empress/empress/__init__.py", line 14, in <module> 
    from empress.xscape.plotcosts_analytic import plot_costs_on_axis as xscape_plot_costs_on_axis 
  File "/Users/sunilkumar/Dropbox/College Docs/Senior Year/research/empress/empress/xscape/plotcosts_analytic.py", line 9, in <module> 
    from shapely.geometry import Polygon, LineString, Point 
  File "/Users/sunilkumar/.local/share/virtualenvs/empress-V6zYLKf0/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module> 
    from .base import CAP_STYLE, JOIN_STYLE 
  File "/Users/sunilkumar/.local/share/virtualenvs/empress-V6zYLKf0/lib/python3.7/site-packages/shapely/geometry/base.py", line 18, in <module> 
    from shapely.coords import CoordinateSequence 
  File "/Users/sunilkumar/.local/share/virtualenvs/empress-V6zYLKf0/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module> 
    from shapely.geos import lgeos 
  File "/Users/sunilkumar/.local/share/virtualenvs/empress-V6zYLKf0/lib/python3.7/site-packages/shapely/geos.py", line 138, in <module> 
    free = load_dll('c').free 
  File "/Users/sunilkumar/.local/share/virtualenvs/empress-V6zYLKf0/lib/python3.7/site-packages/shapely/geos.py", line 62, in load_dll 
    libname, fallbacks or [])) 
OSError: Could not find lib c or load any of its variants []. 
```

**Comment by ssantichaivekin** [comment]
Probably caused by `geos` not being installed in the system. Shapely ships with `geos` since `1.8a1 (2021-03-03)` so updating dependencies might fix this problem.
- If it doesn't work, run `brew install geos` on mac or `sudo apt-get install libgeos-dev` on Liux should fix this problem.
- If we have to install geos manually, don't forget to put it in the documentation.

**Comment by ssantichaivekin** [comment]
Turns out 1.8a1 is not out yet, so we cannot rely on it working. I will add an instruction to install geos manually on the eMPRess website.

**Comment by ssantichaivekin** [comment]
Changed the eMPRess website to link to [Install Empress for Development wiki](https://github.com/ssantichaivekin/empress/wiki/Install-Empress-for-Development). Updated the wiki.

<img width="1556" alt="Screen Shot 2021-06-05 at 5 10 47 PM" src="https://user-images.githubusercontent.com/19219105/120888217-53f94e80-c621-11eb-8639-73bb14ebe4a7.png">
